name: release

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
